# Generated by Django 4.0.3 on 2022-03-12 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.CharField(max_length=30, null=True, verbose_name='Gender')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True, verbose_name='First Name')),
                ('Last_name', models.CharField(max_length=30, null=True, verbose_name='Last Name')),
                ('dob', models.DateField(null=True, verbose_name='Date of Birth')),
                ('email', models.EmailField(max_length=80, null=True, verbose_name='Email')),
                ('phone_number', models.IntegerField(null=True, verbose_name='Phone Number')),
                ('address', models.TextField(null=True, verbose_name='Address')),
                ('city', models.CharField(max_length=80, null=True, verbose_name='City')),
                ('state', models.CharField(max_length=80, null=True, verbose_name='City')),
                ('country', models.CharField(max_length=80, null=True, verbose_name='City')),
                ('pin_code', models.IntegerField(null=True, verbose_name='Pin Code')),
                ('signature', models.FileField(null=True, upload_to='photos/')),
                ('photo', models.FileField(null=True, upload_to='photos/')),
                ('Gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SIH.gender')),
            ],
        ),
    ]
