# Generated by Django 4.0.3 on 2022-03-12 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SIH', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='form',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='form',
            name='signature',
        ),
    ]
