# Generated by Django 4.0.3 on 2022-03-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIH', '0002_remove_form_dob_remove_form_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='dob',
            field=models.DateField(null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='form',
            name='photo',
            field=models.FileField(null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='form',
            name='signature',
            field=models.FileField(null=True, upload_to='photos/'),
        ),
    ]
