# Generated by Django 4.0.3 on 2022-03-12 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SIH', '0003_form_dob_form_photo_form_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='dob',
        ),
    ]
