# Generated by Django 4.0.3 on 2022-03-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIH', '0004_remove_form_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='dob',
            field=models.DateField(null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='form',
            name='country',
            field=models.CharField(max_length=80, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='form',
            name='state',
            field=models.CharField(max_length=80, null=True, verbose_name='State'),
        ),
    ]
