# Generated by Django 3.2.12 on 2022-03-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIH', '0005_form_dob_alter_form_country_alter_form_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='photo',
            field=models.FileField(null=True, upload_to='<django.db.models.fields.EmailField>/photo/'),
        ),
        migrations.AlterField(
            model_name='form',
            name='signature',
            field=models.FileField(null=True, upload_to='<django.db.models.fields.EmailField>/sign/'),
        ),
    ]
