# Generated by Django 3.2.12 on 2022-03-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIH', '0006_auto_20220313_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='photo',
            field=models.FileField(null=True, upload_to='photo/'),
        ),
        migrations.AlterField(
            model_name='form',
            name='signature',
            field=models.FileField(null=True, upload_to='sign/'),
        ),
    ]
