# Generated by Django 3.2.12 on 2022-03-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIH', '0008_auto_20220313_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='signature',
            field=models.FileField(null=True, upload_to='sign/'),
        ),
    ]
