# Generated by Django 3.2.12 on 2022-03-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIH', '0009_form_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='form',
            name='college',
            field=models.CharField(max_length=200, null=True, verbose_name='College Name'),
        ),
        migrations.AddField(
            model_name='form',
            name='course',
            field=models.CharField(max_length=100, null=True, verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='form',
            name='department',
            field=models.CharField(max_length=100, null=True, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='form',
            name='email',
            field=models.EmailField(max_length=80, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='form',
            name='father_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Father Name'),
        ),
        migrations.AddField(
            model_name='form',
            name='mother_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Mother Name'),
        ),
        migrations.AddField(
            model_name='form',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='form',
            name='phone1',
            field=models.IntegerField(max_length=10, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='form',
            name='phone2',
            field=models.IntegerField(max_length=10, null=True, verbose_name='Phone Number 2'),
        ),
        migrations.AddField(
            model_name='form',
            name='registerNo',
            field=models.IntegerField(max_length=10, null=True, verbose_name='Register No'),
        ),
        migrations.AddField(
            model_name='form',
            name='year',
            field=models.CharField(max_length=20, null=True, verbose_name='Year'),
        ),
    ]
