# Generated by Django 3.2.12 on 2022-03-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIH', '0010_auto_20220314_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='info_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True, verbose_name='Name')),
                ('register_no', models.IntegerField(null=True, verbose_name='Register Number')),
                ('batch', models.CharField(max_length=80, null=True, verbose_name='Batch')),
                ('photo', models.FileField(null=True, upload_to='photos/', verbose_name='Photo')),
            ],
        ),
        migrations.AlterField(
            model_name='form',
            name='phone1',
            field=models.IntegerField(null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='form',
            name='phone2',
            field=models.IntegerField(null=True, verbose_name='Phone Number 2'),
        ),
        migrations.AlterField(
            model_name='form',
            name='registerNo',
            field=models.IntegerField(null=True, verbose_name='Register No'),
        ),
    ]
