# Generated by Django 4.0.3 on 2022-03-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIH', '0011_auto_20220315_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='email',
            field=models.EmailField(max_length=80, null=True, unique=True, verbose_name='Email'),
        ),
    ]
